openapi: 3.0.3
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/'
paths:
  /v1/me/accounts:
    get:
      summary: Просмотр счетов пользователя
      tags:
        - User data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/accounts/open:
    post:
      summary: Открытие счёта
      tags:
        - Account operations
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Created
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        internalCode:
          type: string
          description: Внутренний код ошибки
        devMessage:
          type: string
          description: Сообщение для разработчика
        userMessage:
          type: string
          description: Сообщение для пользователя

    AccountsResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          balanceCents:
            type: integer
          status:
            type: string
        required:
          - id
          - balanceCents
          - status
